plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.4'
}

repositories {
    mavenCentral()
}


dependencies {
    implementation project(':thrift')
    implementation 'org.apache.thrift:libthrift:0.19.0'
    implementation 'org.springframework.boot:spring-boot-starter-web'
}

java {
    sourceCompatibility = '17'
}