movieThriftUrl=http://localhost:8080/thrift/thrift/movie
movieVirtualUrl=http://localhost:8080/virtual
clientThrift=moviemashup.client.implement.ClientThrift
clientVirtual=moviemashup.client.implement.ClientVirtual